import { InspectionItem, ZipFile } from "./types"

export const mockInspectionItems: InspectionItem[] = [
  {
    id: "1",
    productCode: "A1001",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "애호박",
    supplier: "농협",
    orderQuantity: 50,
    inspectedQuantity: 30,
    returnQuantity: 2,
    exchangeQuantity: 1,
    inspectionPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    defectPhotos: ["/placeholder.svg?height=100&width=100"],
    weightPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessPhotos: [],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: true,
    inspectedAt: "2024.04.24 10:30",
    hasPhoto: true,
  },
  {
    id: "2",
    productCode: "A1002",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "완숙토마토",
    supplier: "농협",
    orderQuantity: 40,
    inspectedQuantity: 25,
    returnQuantity: 1,
    exchangeQuantity: 0,
    inspectionPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    defectPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    weightPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: true,
    inspectedAt: "2024.04.23 16:10",
    hasPhoto: true,
  },
  {
    id: "3",
    productCode: "A1003",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "양배추",
    supplier: "농협",
    orderQuantity: 60,
    inspectedQuantity: 60,
    returnQuantity: 0,
    exchangeQuantity: 0,
    inspectionPhotos: [],
    defectPhotos: [],
    weightPhotos: [],
    sweetnessPhotos: [],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: false,
    hasPhoto: false,
  },
  {
    id: "4",
    productCode: "B2001",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "감자",
    supplier: "남도농산",
    orderQuantity: 100,
    inspectedQuantity: 80,
    returnQuantity: 0,
    exchangeQuantity: 0,
    inspectionPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    defectPhotos: [],
    weightPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessPhotos: ["/placeholder.svg?height=100&width=100"],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: true,
    inspectedAt: "2024.04.24 09:20",
    hasPhoto: true,
  },
  {
    id: "5",
    productCode: "B2002",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "당근",
    supplier: "남도농산",
    orderQuantity: 70,
    inspectedQuantity: 70,
    returnQuantity: 0,
    exchangeQuantity: 0,
    inspectionPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    defectPhotos: [],
    weightPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessPhotos: ["/placeholder.svg?height=100&width=100"],
    sweetnessMin: 8.2,
    sweetnessMax: 11.4,
    isCompleted: true,
    inspectedAt: "2024.04.23 11:40",
    hasPhoto: true,
  },
  {
    id: "6",
    productCode: "C3001",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "사과",
    supplier: "경북과수",
    orderQuantity: 120,
    inspectedQuantity: 118,
    returnQuantity: 2,
    exchangeQuantity: 0,
    inspectionPhotos: ["/placeholder.svg?height=100&width=100"],
    defectPhotos: ["/placeholder.svg?height=100&width=100"],
    weightPhotos: ["/placeholder.svg?height=100&width=100"],
    sweetnessPhotos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    sweetnessMin: 14.0,
    sweetnessMax: 15.8,
    isCompleted: true,
    inspectedAt: "2024.04.22 14:30",
    hasPhoto: true,
  },
  {
    id: "7",
    productCode: "D4001",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "한우 등심 600g",
    supplier: "한우마을",
    orderQuantity: 30,
    inspectedQuantity: 0,
    returnQuantity: 0,
    exchangeQuantity: 0,
    inspectionPhotos: [],
    defectPhotos: [],
    weightPhotos: [],
    sweetnessPhotos: [],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: false,
    hasPhoto: false,
  },
  {
    id: "8",
    productCode: "E5001",
    productImage: "/placeholder.svg?height=60&width=60",
    productName: "노르웨이 연어 500g",
    supplier: "바다수산",
    orderQuantity: 40,
    inspectedQuantity: 0,
    returnQuantity: 0,
    exchangeQuantity: 0,
    inspectionPhotos: [],
    defectPhotos: [],
    weightPhotos: [],
    sweetnessPhotos: [],
    sweetnessMin: null,
    sweetnessMax: null,
    isCompleted: false,
    hasPhoto: false,
  },
]

export const mockZipFiles: ZipFile[] = [
  { name: "photo_1.zip", size: "19.8MB" },
  { name: "photo_2.zip", size: "19.7MB" },
  { name: "photo_3.zip", size: "8.2MB" },
]
